logging:
  level:
    root: info
    org.springframework.data: debug
    org.springframework.security: debug

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/pgDatabase
      username: user
      password: password
      driver-class-name: org.postgresql.Driver
    data: classpath:data.sql
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc:
          batch_size: 20

---

spring:
  config:
    activate:
      on-profile: h2
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password: password
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc:
          batch_size: 20
