logging:
  level:
    root: info
    org.springframework.data: debug

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password: password
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc:
          batch_size: 20
